apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-one-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-one-app
  template:
    metadata:
      labels:
        app: task-one-app
    spec:
      containers:
        - name: task-one-app
          image: pportu/task_one:1.0.0
          ports:
            - containerPort: 80
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/t_sem_two
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
          imagePullPolicy: Always
      restartPolicy: Always
      