apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: task-one-postgresdb-service
spec:
  selector:
    app: task-one-postgresdb
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-one-postgresdb
spec:
  selector:
    matchLabels:
      app: task-one-postgresdb
  replicas: 1
  template:
    metadata:
      labels:
        app: task-one-postgresdb
    spec:
      containers:
        - name: task-one-postgresdb
          image: postgres:14-alpine3.18
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: t-sem-two
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: t_sem_two
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
      volumes:
        - name: t-sem-two
          persistentVolumeClaim:
            claimName: postgres-pvc

  